import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    
    'brutalist-container',
    'brutalist-section',
    'brutalist-grid',
    'brutalist-flex',
    'brutalist-card',
    'brutalist-card-sm',
    'brutalist-card-lg',
    'brutalist-button',
    'brutalist-button-secondary',
    'brutalist-button-sm',
    'brutalist-input',
    'brutalist-textarea',
    'brutalist-select',
    'brutalist-select-content',
    'brutalist-sidebar',
    'brutalist-sidebar-header',
    'brutalist-sidebar-nav',
    'brutalist-sidebar-footer',
    'brutalist-header',
    'brutalist-nav-item',
    'brutalist-nav-item-active',
    'text-brutalist',
    'text-brutalist-lg',
    'text-brutalist-sm',
    'brutalist-badge',
    'brutalist-badge-success',
    'brutalist-badge-warning',
    'brutalist-badge-error',
    'brutalist-badge-info',
    'brutalist-alert',
    'brutalist-alert-success',
    'brutalist-alert-error',
    'brutalist-alert-warning',
    'brutalist-alert-info',
    'brutalist-empty',
    'brutalist-empty-icon',
    'brutalist-empty-title',
    'brutalist-empty-description',
    'brutalist-status-dot',
    'brutalist-status-active',
    'brutalist-status-inactive',
    'brutalist-status-pending',
    'brutalist-loading',
    'brutalist-stat-card',
    'brutalist-hover',
    'brutalist-hover-lg',
    'brutalist-shadow',
    'font-brutalist',
    'tracking-brutalist',
    'tracking-brutalist-lg',
    'tracking-brutalist-sm',
    'shadow-brutalist',
    'shadow-brutalist-lg',
    'shadow-brutalist-sm',
  ],
};
export default config;